{
	"version": 1615613437,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/arrow-sheet0.png",
		"images/center1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/ui-sheet0.png",
		"images/replay-sheet0.png",
		"images/ui4-sheet0.png",
		"images/ui5-sheet0.png",
		"images/position-sheet0.png",
		"images/ui8-sheet0.png",
		"images/play-sheet0.png",
		"images/rules-sheet0.png",
		"images/sound-sheet0.png",
		"images/exit-sheet0.png",
		"images/gui-sheet0.png",
		"images/gui2-sheet0.png",
		"images/gui3-sheet0.png",
		"images/gui4-sheet0.png",
		"images/gui5-sheet0.png",
		"images/gui6-sheet0.png",
		"images/buttonlevel-sheet0.png",
		"images/buttonlevel-sheet1.png",
		"images/level2-sheet0.png",
		"images/level3-sheet0.png",
		"images/symbol-sheet0.png",
		"images/ui14-sheet0.png",
		"images/ui15-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sponser-sheet0.png",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/levelcomplete.m4a",
		"media/levelcomplete.ogg",
		"media/392252__setuniman__smart-1p10.m4a",
		"media/392252__setuniman__smart-1p10.ogg",
		"media/hit (1).m4a",
		"media/hit (1).ogg",
		"media/shoot (1).m4a",
		"media/shoot (1).ogg",
		"media/hitt.m4a",
		"media/hitt.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}